## 1.Create a 1D NumPy array with integers from 1 to 20. Perform the following operations

In [7]:
import numpy as np
arr = np.arange(1,21)
print(arr)
sum = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
print("\n",sum,"\n",mean,"\n",median,"\n",std_dev)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 210 
 10.5 
 10.5 
 5.766281297335398


In [8]:
indices = [ i for i in range (len(arr)) if arr[i] > 10]
print(arr[indices])

[11 12 13 14 15 16 17 18 19 20]


## 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  


In [9]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
Transpose = np.transpose(arr2)
Transpose

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [11]:
sum_row = np.sum(arr2,axis = 1)
sum_row

array([10, 26, 42, 58])

In [12]:
sum_column = np.sum(arr2,axis = 0)
sum_column

array([28, 32, 36, 40])

## 3.Create two 3 X 3 arrays filled with random integers between 1 and 20

In [21]:
arr3 = np.random.randint(1,21,(3,3))
arr4 = np.random.randint(1,21,(3,3))
arr3,arr4

(array([[ 3,  4,  4],
        [17,  2, 11],
        [12,  6,  1]], dtype=int32),
 array([[20,  1, 14],
        [14,  8,  3],
        [11, 10, 10]], dtype=int32))

In [24]:
addition = arr3 + 5
print("addition")
print(addition,"\n")
mul = arr3 * 5
print("Multiplication")
print(mul,"\n")
sub = arr3 - 5
print("Subtraction")
print(sub,"\n")
dot_product = np.dot(arr3,arr4)
print("dot_product")
print(dot_product)

addition
[[ 8  9  9]
 [22  7 16]
 [17 11  6]] 

Multiplication
[[15 20 20]
 [85 10 55]
 [60 30  5]] 

Subtraction
[[-2 -1 -1]
 [12 -3  6]
 [ 7  1 -4]] 

dot_product
[[160  75  94]
 [489 143 354]
 [335  70 196]]


## 4.Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [27]:
arr4 = np.arange(12)
reshaped_arr = arr4.reshape(3, 4)
print("Reshaped 3x4 array:")
print(reshaped_arr)
sliced_arr = reshaped_arr[0:2, 2:4]
print("\nSliced array (first two rows and last two columns):")
print(sliced_arr)

Reshaped 3x4 array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sliced array (first two rows and last two columns):
[[2 3]
 [6 7]]
